### ISSUE TITLE
Couldn't start the dev server

### ISSUE THREAD

**Issue by xerod** [Schniz/remastered#41]
## Describe the bug

`npx remastered dev` wouldn't start the server:

```
[Error: ENOENT: no such file or directory, open '/Users/mypc/Sites/remastered-twitter-clone/node_modules/remastered/src/entry-server.tsx'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/mypc/Sites/remastered-twitter-clone/node_modules/remastered/src/entry-server.tsx'
}
```

 I believe Vite is causing this when the original Typescript sources doesn't included in the package but being referenced in the source map. See [vitejs/vite#2892](https://github.com/vitejs/vite/issues/2892)

The server works just fine when you remove all the source maps (with vite telling they're failed to load the source maps):
`find node_modules/remastered/dist/ -name \"*.js.map\" -type f -delete` 

## Reproduction
Following the Getting Started guide [here](https://remastered.hagever.com/docs/welcome/getting-started), and try to run dev server.

## Suggested Solution
Fix the source maps

## Additional Context
Great work man 👍🏽  I hope people can start using it as soon as possible

**Comment by Schniz** [comment]
Hi! I'm fixing something in the build process. I think I blew it up. Can't trust package e2e tests in a monorepo. Hope to fix it by tomorrow 🥲 sorry and thanks, will update here!

**Comment by Schniz** [comment]
https://github.com/Schniz/remastered/releases/tag/v0.1.29 is published with sources included so sourcemaps will work. Maybe I need to set up https://www.typescriptlang.org/tsconfig#inlineSources to get proper sourcemaps? Sounds like a bad idea though. Would rather put the sources in the library. Maybe I don't need to distribute the sourcemaps at all for the library itself?

Anyway this is fixed! Try the newest version! 😃
